version: "3.9"

services:
    todo-app:
        container_name: todo-app
        image: hgrafa/todo-app:latest
        build: .
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db
        volumes:
            - .:/var/www/html

    db:
        container_name: db
        image: postgres:16
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: ncQ5wId1
            POSTGRES_DB: todo_db
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
